# Generated by Django 6.0.4 on 2026-04-09 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('source_type', models.CharField(choices=[('markdown', 'Markdown'), ('pdf', 'PDF')], db_index=True, max_length=20)),
                ('source_file', models.FileField(upload_to='uploads/posts/%Y/%m/%d/')),
                ('content_markdown', models.TextField(blank=True)),
                ('content_text', models.TextField(blank=True)),
                ('content_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
