# Generated by Django 6.0.4 on 2026-04-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='source_file',
            field=models.FileField(upload_to='document/'),
        ),
    ]
